server.port=8080
spring.application.name=api-gateway

# Eureka server address
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedOrigins=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedMethods=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedHeaders=*

spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://auth-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

spring.cloud.gateway.routes[1].id=patient-service
spring.cloud.gateway.routes[1].uri=lb://patient-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/patients/**

spring.cloud.gateway.routes[2].id=doctor-service
spring.cloud.gateway.routes[2].uri=lb://doctor-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/doctors/**

spring.cloud.gateway.routes[3].id=rendezvous-service
spring.cloud.gateway.routes[3].uri=lb://rendezvous-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/rendezvous/**

spring.cloud.gateway.routes[4].id=facture-service
spring.cloud.gateway.routes[4].uri=lb://facture-service
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/factures/**

# meme secret que dans auth-service
jwt.secret=KJH76DHDJSHD73JSHDHS72HS8DJSHD82JSHDHSYE62HS8DJSHDHS72HS8DJSHDHS
