server.port=8084
spring.application.name=rendezvous-service

spring.datasource.url=jdbc:h2:mem:rdvdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.h2.console.enabled=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
management.endpoints.web.exposure.include=*

resilience4j.circuitbreaker.instances.rendezvousCB.sliding-window-size=5
resilience4j.circuitbreaker.instances.rendezvousCB.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.rendezvousCB.wait-duration-in-open-state=10s

resilience4j.retry.instances.rendezvousRetry.max-attempts=3
resilience4j.retry.instances.rendezvousRetry.wait-duration=500ms
